[build-system]
build-backend = "pdm.backend"

requires = [
  "pdm-backend",
]

[project]
name = "dyu"
description = "A wrapper click script for setting up everything related to dyumnin semiconductors projects."
readme = "README.md"
keywords = [
  "copier-template",
  "full-development-lifecycle",
  "project-template",
  "serious-scaffold",
]
license = { text = "MIT" }
authors = [
  { email = "jahagirdar.vs@gmail.com", name = "Vijayvithal Jahagirdar" },
]
requires-python = ">=3.10"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

dynamic = [
  "version",
]
dependencies = [
  "copier>=9.3.1",
  "pydantic-settings",
  "requests",
  "typer[all]",
  "xdg-base-dirs",
]
urls.Documentation = "https://dyumnin.github.io/dyu"
urls.Issue = "https://github.com/dyumnin/dyu/issues"
urls.Repository = "https://github.com/dyumnin/dyu"
scripts.dyu = "dyu.cli:app"

[tool.pdm]
distribution = true
[tool.pdm.version]
source = "scm"
version_format = "version:format_version"

[tool.pdm.dev-dependencies]
lint = [
  "mypy",
  "ruff",
]
test = [
  "coverage",
  "pytest",
]

[dependency-groups]
doc = [
    "markdown-callouts>=0.3",
    "markdown-exec>=1.7",
    "mkdocs>=1.5",
    "mkdocs-material>=9.6.9",
    "mkdocs-coverage>=1.0",
    "mkdocs-gen-files>=0.5",
    "mkdocs-git-committers-plugin-2>=1.2",
    "mkdocs-literate-nav>=0.6",
    "mkdocs-material>=9.4",
    "mkdocs-minify-plugin>=0.7",
    "mkdocstrings[python]>=0.23",
    "tomli>=2.0; python_version < '3.11'",
]
